using System.Collections.Generic;
using Sandbox.ModAPI.Ingame;
using VRage.Game;
using VRage.Game.ModAPI.Ingame;

namespace IngameScript
{
    public partial class Program : MyGridProgram
    {
        const string AM = "AmmoMagazine";
        const string PGO = "PhysicalGunObject";
        const string C = "Component";
        const string CI = "ConsumableItem";

        struct Meta
        {
            public MyDefinitionId BlueprintId;
            public MyItemType TypeId;
            public Meta(string blueprintId, string itemType) {
                BlueprintId = MyDefinitionId.Parse($"MyObjectBuilder_BlueprintDefinition/{blueprintId}");
                TypeId = MyItemType.Parse($"MyObjectBuilder_{itemType}");
            }
        }
        Dictionary<string, Meta> Items = new Dictionary<string, Meta> {
            {"Advanced Hand Held Launcher"            , new Meta("Position0090_AdvancedHandHeldLauncher"           , $"{PGO}/AdvancedHandHeldLauncherItem")},
            {"Angle Grinder 2"                        , new Meta("Position0020_AngleGrinder2"                      , $"{PGO}/AngleGrinder2Item")},
            {"Angle Grinder 3"                        , new Meta("Position0030_AngleGrinder3"                      , $"{PGO}/AngleGrinder3Item")},
            {"Angle Grinder 4"                        , new Meta("Position0040_AngleGrinder4"                      , $"{PGO}/AngleGrinder4Item")},
            {"Angle Grinder"                          , new Meta("Position0010_AngleGrinder"                       , $"{PGO}/AngleGrinderItem")},
            {"AutoCannon Clip"                        , new Meta("Position0090_AutocannonClip"                     , $"{AM}/AutocannonClip")},
            {"Automatic Rifle Gun Mag 20rd"           , new Meta("Position0040_AutomaticRifleGun_Mag_20rd"         , $"{AM}/AutomaticRifleGun_Mag_20rd")},
            {"Automatic Rifle"                        , new Meta("Position0040_AutomaticRifle"                     , $"{PGO}/AutomaticRifleItem")},
            {"Basic Hand Held Launcher"               , new Meta("Position0080_BasicHandHeldLauncher"              , $"{PGO}/BasicHandHeldLauncherItem")},
            {"Bulletproof Glass"                      , new Meta("BulletproofGlass"                                , $"{C}/BulletproofGlass")},
            {"Burrito"                                , new Meta("Position0170_MealPack_Burrito"                   , $"{CI}/MealPack_Burrito")},
            {"Canvas Cartridge"                       , new Meta("Position0030_Canvas"                             , $"{C}/Canvas")},
            {"Chili"                                  , new Meta("Position0070_MealPack_Chili"                     , $"{CI}/MealPack_Chili")},
            {"Cobalt Ingot"                           , new Meta("CobaltOreToIngot"                                , "Ingot/Cobalt")},
            {"Computer"                               , new Meta("ComputerComponent"                               , $"{C}/Computer")},
            {"Construction Component"                 , new Meta("ConstructionComponent"                           , $"{C}/Construction")},
            {"Cooked Mammal Meat"                     , new Meta("Position0010_CookMammalMeat"                     , $"{CI}/MammalMeatCooked")},
            {"Cooked Spider Meat"                     , new Meta("Position0020_CookSpiderMeat"                     , $"{CI}/InsectMeatCooked")},
            {"Curry"                                  , new Meta("Position0120_MealPack_Curry"                     , $"{CI}/MealPack_Curry")},
            {"Datapad"                                , new Meta("Position0040_Datapad"                            , "Datapad/Datapad")},
            {"Detector Components"                    , new Meta("DetectorComponent"                               , $"{C}/Detector")},
            {"Display"                                , new Meta("Display"                                         , $"{C}/Display")},
            {"Dumplings"                              , new Meta("Position0140_MealPack_Dumplings"                 , $"{CI}/MealPack_Dumplings")},
            {"Elite Automatic Rifle"                  , new Meta("Position0070_UltimateAutomaticRifle"             , $"{PGO}/UltimateAutomaticRifleItem")},
            {"Elite Pistol Magazine"                  , new Meta("Position0030_ElitePistolMagazine"                , $"{AM}/ElitePistolMagazine")},
            {"Elite Pistol"                           , new Meta("Position0030_EliteAutoPistol"                    , $"{PGO}/ElitePistolItem")},
            {"Engineer Plushie"                       , new Meta("EngineerPlushie"                                 , $"{C}/EngineerPlushie")},
            {"Explosives"                             , new Meta("ExplosivesComponent"                             , $"{C}/Explosives")},
            {"Fireworks Box Blue"                     , new Meta("Position0060_FireworksBoxBlue"                   , $"{AM}/FireworksBoxBlue")},
            {"Fireworks Box Green"                    , new Meta("Position0061_FireworksBoxGreen"                  , $"{AM}/FireworksBoxGreen")},
            {"Fireworks Box Pink"                     , new Meta("Position0064_FireworksBoxPink"                   , $"{AM}/FireworksBoxPink")},
            {"Fireworks Box Rainbow"                  , new Meta("Position0065_FireworksBoxRainbow"                , $"{AM}/FireworksBoxRainbow")},
            {"Fireworks Box Red"                      , new Meta("Position0062_FireworksBoxRed"                    , $"{AM}/FireworksBoxRed")},
            {"Fireworks Box Yellow"                   , new Meta("Position0063_FireworksBoxYellow"                 , $"{AM}/FireworksBoxYellow")},
            {"Flare Clip"                             , new Meta("Position0051_FlareGunMagazine"                   , $"{AM}/FlareClip")},
            {"Flare Gun"                              , new Meta("Position0050_FlareGun"                           , $"{PGO}/FlareGunItem")},
            {"Flatbread"                              , new Meta("Position0080_MealPack_Flatbread"                 , $"{CI}/MealPack_Flatbread")},
            {"Frontier Stew"                          , new Meta("Position0180_MealPack_FrontierStew"              , $"{CI}/MealPack_FrontierStew")},
            {"Fruit Bar"                              , new Meta("Position0040_MealPack_FruitBar"                  , $"{CI}/MealPack_FruitBar")},
            {"Fruit Pastry"                           , new Meta("Position0100_MealPack_FruitPastry"               , $"{CI}/MealPack_FruitPastry")},
            {"Fruit Seeds"                            , new Meta("Position0010_Seeds_Fruit"                        , "SeedItem/Fruit")},
            {"Full-Auto Pistol Magazine"              , new Meta("Position0020_FullAutoPistolMagazine"             , $"{AM}/FullAutoPistolMagazine")},
            {"Full-Auto Pistol"                       , new Meta("Position0020_FullAutoPistol"                     , $"{PGO}/FullAutoPistolItem")},
            {"Garden Slaw"                            , new Meta("Position0050_MealPack_GardenSlaw"                , $"{CI}/MealPack_GardenSlaw")},
            {"Girder"                                 , new Meta("GirderComponent"                                 , $"{C}/Girder")},
            {"Gold Ingot"                             , new Meta("GoldOreToIngot"                                  , "Ingot/Gold")},
            {"Grain Seeds"                            , new Meta("Position0020_Seeds_Grain"                        , "SeedItem/Grain")},
            {"Gravity Generator Components"           , new Meta("GravityGeneratorComponent"                       , $"{C}/GravityGenerator")},
            {"Green Pellets"                          , new Meta("Position0130_MealPack_GreenPellets"              , $"{CI}/MealPack_GreenPellets")},
            {"Hand Drill 2"                           , new Meta("Position0060_HandDrill2"                         , $"{PGO}/HandDrill2Item")},
            {"Hand Drill 3"                           , new Meta("Position0070_HandDrill3"                         , $"{PGO}/HandDrill3Item")},
            {"Hand Drill 4"                           , new Meta("Position0080_HandDrill4"                         , $"{PGO}/HandDrill4Item")},
            {"Hand Drill"                             , new Meta("Position0050_HandDrill"                          , $"{PGO}/HandDrillItem")},
            {"Hydrogen Bottle"                        , new Meta("Position0020_HydrogenBottle"                     , "GasContainerObject/HydrogenBottle")},
            {"Interior Plate"                         , new Meta("InteriorPlate"                                   , $"{C}/InteriorPlate")},
            {"Iron Ingot"                             , new Meta("IronOreToIngot"                                  , "Ingot/Iron")},
            {"Kelp Crisp"                             , new Meta("Position0030_MealPack_KelpCrisp"                 , $"{CI}/MealPack_KelpCrisp")},
            {"Large Calibre Ammo"                     , new Meta("Position0120_LargeCalibreAmmo"                   , $"{AM}/LargeCalibreAmmo")},
            {"Large Railgun Ammo"                     , new Meta("Position0140_LargeRailgunAmmo"                   , $"{AM}/LargeRailgunAmmo")},
            {"Large Steel Tube"                       , new Meta("LargeTube"                                       , $"{C}/LargeTube")},
            {"Lasagna"                                , new Meta("Position0160_MealPack_Lasagna"                   , $"{CI}/MealPack_Lasagna")},
            {"Magnesium Powder"                       , new Meta("MagnesiumOreToIngot"                             , "Ingot/Magnesium")},
            {"Medical Components"                     , new Meta("MedicalComponent"                                , $"{C}/Medical")},
            {"Medium Calibre Ammo"                    , new Meta("Position0110_MediumCalibreAmmo"                  , $"{AM}/MediumCalibreAmmo")},
            {"Medkit"                                 , new Meta("Position0021_Medkit"                             , $"{CI}/Medkit")},
            {"Metal Grid"                             , new Meta("MetalGrid"                                       , $"{C}/MetalGrid")},
            {"Missile 200mm"                          , new Meta("Position0100_Missile200mm"                       , $"{AM}/Missile200mm")},
            {"Motor"                                  , new Meta("MotorComponent"                                  , $"{C}/Motor")},
            {"Mushroom Spores"                        , new Meta("Position0040_Spores_Mushrooms"                   , "SeedItem/Mushrooms")},
            {"NATO 25x184mm"                          , new Meta("Position0080_NATO_25x184mmMagazine"              , $"{AM}/NATO_25x184mm")},
            {"Nickel Ingot"                           , new Meta("NickelOreToIngot"                                , "Ingot/Nickel")},
            {"Oxygen Bottle"                          , new Meta("Position0010_OxygenBottle"                       , "OxygenContainerObject/OxygenBottle")},
            {"Platinum Ingot"                         , new Meta("PlatinumOreToIngot"                              , "Ingot/Platinum")},
            {"Power Cell"                             , new Meta("PowerCell"                                       , $"{C}/PowerCell")},
            {"Powerkit"                               , new Meta("Position0022_Powerkit"                           , $"{CI}/Powerkit")},
            {"Precise Automatic Rifle Gun Mag 5rd"    , new Meta("Position0060_PreciseAutomaticRifleGun_Mag_5rd"   , $"{AM}/PreciseAutomaticRifleGun_Mag_5rd")},
            {"Precise Automatic Rifle"                , new Meta("Position0060_PreciseAutomaticRifle"              , $"{PGO}/PreciseAutomaticRifleItem")},
            {"Prototech Capacitor"                    , new Meta("PrototechCapacitor"                              , $"{C}/PrototechCapacitor")},
            {"Prototech Circuitry"                    , new Meta("PrototechCircuitry"                              , $"{C}/PrototechCircuitry")},
            {"Prototech Cooling Unit"                 , new Meta("PrototechCoolingUnit"                            , $"{C}/PrototechCoolingUnit")},
            {"Prototech Frame"                        , new Meta("PrototechFrame"                                  , $"{C}/PrototechFrame")},
            {"Prototech Machinery"                    , new Meta("PrototechMachinery"                              , $"{C}/PrototechMachinery")},
            {"Prototech Panel"                        , new Meta("PrototechPanel"                                  , $"{C}/PrototechPanel")},
            {"Prototech Propulsion Unit"              , new Meta("PrototechPropulsionUnit"                         , $"{C}/PrototechPropulsionUnit")},
            {"Radio Communication Components"         , new Meta("RadioCommunicationComponent"                     , $"{C}/RadioCommunication")},
            {"Ramen"                                  , new Meta("Position0090_MealPack_Ramen"                     , $"{CI}/MealPack_Ramen")},
            {"Rapid-Fire Automatic Rifle Gun Mag 50rd", new Meta("Position0050_RapidFireAutomaticRifleGun_Mag_50rd", $"{AM}/RapidFireAutomaticRifleGun_Mag_50rd")},
            {"Rapid-Fire Automatic Rifle"             , new Meta("Position0050_RapidFireAutomaticRifle"            , $"{PGO}/RapidFireAutomaticRifleItem")},
            {"Reactor Components"                     , new Meta("ReactorComponent"                                , $"{C}/Reactor")},
            {"Red Pellets"                            , new Meta("Position0060_MealPack_RedPellets"                , $"{CI}/MealPack_RedPellets")},
            {"Sabiroid Plushie"                       , new Meta("SabiroidPlushie"                                 , $"{C}/SabiroidPlushie")},
            {"Seared Sabiroid"                        , new Meta("Position0190_MealPack_SearedSabiroid"            , $"{CI}/MealPack_SearedSabiroid")},
            {"Semi-Auto Pistol Magazine"              , new Meta("Position0010_SemiAutoPistolMagazine"             , $"{AM}/SemiAutoPistolMagazine")},
            {"Semi-Auto Pistol"                       , new Meta("Position0010_SemiAutoPistol"                     , $"{PGO}/SemiAutoPistolItem")},
            {"Silicon Wafer"                          , new Meta("SiliconOreToIngot"                               , "Ingot/Silicon")},
            {"Silver Ingot"                           , new Meta("SilverOreToIngot"                                , "Ingot/Silver")},
            {"Small Railgun Ammo"                     , new Meta("Position0130_SmallRailgunAmmo"                   , $"{AM}/SmallRailgunAmmo")},
            {"Small Steel Tube"                       , new Meta("SmallTube"                                       , $"{C}/SmallTube")},
            {"Solar Cell"                             , new Meta("SolarCell"                                       , $"{C}/SolarCell")},
            {"Spaghetti"                              , new Meta("Position0150_MealPack_Spaghetti"                 , $"{CI}/MealPack_Spaghetti")},
            {"Steak Dinner"                           , new Meta("Position0200_MealPack_SteakDinner"               , $"{CI}/MealPack_SteakDinner")},
            {"Steel Plate"                            , new Meta("SteelPlate"                                      , $"{C}/SteelPlate")},
            {"Superconductor"                         , new Meta("Superconductor"                                  , $"{C}/Superconductor")},
            {"Thrust Components"                      , new Meta("ThrustComponent"                                 , $"{C}/Thrust")},
            {"Ultimate Automatic Rifle Gun Mag 30rd"  , new Meta("Position0070_UltimateAutomaticRifleGun_Mag_30rd" , $"{AM}/UltimateAutomaticRifleGun_Mag_30rd")},
            {"Uranium Ingot"                          , new Meta("UraniumOreToIngot"                               , "Ingot/Uranium")},
            {"Vegetable Seeds"                        , new Meta("Position0030_Seeds_Vegetables"                   , "SeedItem/Vegetables")},
            {"Veggie Burger"                          , new Meta("Position0110_MealPack_VeggieBurger"              , $"{CI}/MealPack_VeggieBurger")},
            {"Welder 2"                               , new Meta("Position0100_Welder2"                            , $"{PGO}/Welder2Item")},
            {"Welder 3"                               , new Meta("Position0110_Welder3"                            , $"{PGO}/Welder3Item")},
            {"Welder 4"                               , new Meta("Position0120_Welder4"                            , $"{PGO}/Welder4Item")},
            {"Welder"                                 , new Meta("Position0090_Welder"                             , $"{PGO}/WelderItem")},
            {"Zone Chip"                              , new Meta("ZoneChip"                                        , $"{C}/ZoneChip")},
        };
    }
}